import { useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { lovable } from '@/integrations/lovable/index';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
export function FootballSignIn({open,onOpenChange}:{open:boolean;onOpenChange:(v:boolean)=>void}) {
 const [signup,setSignup]=useState(false); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{signup?'Create an account':'Sign in to save your clubs'}</DialogTitle><DialogDescription>Private Football Management workspace</DialogDescription></DialogHeader><Button variant="outline" disabled={busy} onClick={async()=>{setBusy(true);setMessage('');const result=await lovable.auth.signInWithOAuth('google',{redirect_uri:window.location.origin});setBusy(false);if(result.error)setMessage(result.error.message);else if(!result.redirected)onOpenChange(false)}}>Continue with Google</Button><form className="space-y-4" onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');const result=signup?await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin}}):await supabase.auth.signInWithPassword({email,password});setBusy(false);if(result.error)setMessage(result.error.message);else if(result.data.session)onOpenChange(false);else setMessage('Check your email to confirm your account, then sign in.')}}><div><Label htmlFor="football-email">Email</Label><Input id="football-email" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></div><div><Label htmlFor="football-password">Password</Label><Input id="football-password" type="password" minLength={8} autoComplete={signup?'new-password':'current-password'} required value={password} onChange={e=>setPassword(e.target.value)}/></div><p role="status" className="text-sm text-muted-foreground">{message}</p><Button className="w-full" disabled={busy}>{busy?'Please wait…':signup?'Create account':'Sign in'}</Button></form><Button variant="ghost" onClick={()=>{setSignup(!signup);setMessage('')}}>{signup?'Already registered? Sign in':'Create an account'}</Button></DialogContent></Dialog>;
}
