export type FootballRow = { id: string; [key: string]: string };
export type FootballField = { key: string; label: string; type?: 'number' | 'date' | 'textarea' | 'select'; options?: string[] };
export type FootballSection = { id: string; title: string; singular: string; fields: FootballField[]; seed: Record<string, string>[] };
const field = (key: string, label: string, type?: FootballField['type'], options?: string[]): FootballField => ({ key, label, type, options });
export const footballSections: FootballSection[] = [
 { id: 'players', title: 'Player Performance', singular: 'Player', fields: [field('name','Player name'),field('position','Position','select',['Goalkeeper','Defender','Midfielder','Forward']),field('goals','Goals','number'),field('assists','Assists','number'),field('minutes','Minutes played','number'),field('fitness','Fitness (%)','number'),field('attendance','Training attendance (%)','number'),field('discipline','Discipline record','textarea'),field('contract','Contract review date','date'),field('notes','Development notes','textarea')], seed:[{name:'Daniel Otieno',position:'Forward',goals:'9',assists:'4',minutes:'1080',fitness:'92',attendance:'96',discipline:'1 yellow card',contract:'2025-12-31',notes:'Consistent finishing; review promotion.'},{name:'Kevin Mwangi',position:'Midfielder',goals:'3',assists:'7',minutes:'990',fitness:'84',attendance:'90',discipline:'No incidents',notes:'Improve endurance.'}] },
 { id:'goals',title:'Team Goals',singular:'Goal',fields:[field('name','Goal name'),field('metric','Success measure'),field('current','Current value','number'),field('target','Target value','number'),field('owner','Owner'),field('cadence','Milestone cadence','select',['Weekly','Monthly','Season']),field('due','Target date','date'),field('milestones','Milestones and progress','textarea'),field('status','Status','select',['Planning','On track','At risk','Completed'])],seed:[{name:'Develop academy talent',metric:'Senior team promotions',current:'2',target:'5',owner:'Head Coach',cadence:'Monthly',due:'2025-12-31',status:'On track',milestones:'Two players promoted; three in senior training.'},{name:'Grow matchday attendance',metric:'Average fans per match',current:'2400',target:'3500',owner:'Commercial Manager',cadence:'Monthly',status:'At risk'}]},
 {id:'staff',title:'Staff Management',singular:'Staff member',fields:[field('name','Staff name'),field('role','Role','select',['Coach','Medic','Analyst','Scout','Media','Administrator']),field('department','Department'),field('attendance','Attendance (%)','number'),field('productivity','Productivity (%)','number'),field('task','Assigned task'),field('due','Task due date','date'),field('status','Task status','select',['Pending','In progress','Completed']),field('report','Department report','textarea'),field('review','Performance review','textarea'),field('development','Development plan','textarea')],seed:[{name:'Grace Achieng',role:'Coach',department:'Academy',attendance:'98',productivity:'88',task:'Prepare U19 training plan',status:'In progress',development:'Complete coaching qualification.'}]},
 {id:'finance',title:'Financial Oversight',singular:'Transaction',fields:[field('name','Transaction name'),field('type','Type','select',['Income','Expense','Budget']),field('category','Category','select',['Sponsorship','Matchday revenue','Player wages','Transfers','Operations','Academy']),field('amount','Amount (KES)','number'),field('date','Date','date'),field('owner','Responsible person'),field('status','Status','select',['Planned','Paid','Received']),field('notes','Notes','textarea')],seed:[{name:'Season sponsor payment',type:'Income',category:'Sponsorship',amount:'2500000',date:'2025-09-01',status:'Received'},{name:'Squad wages',type:'Expense',category:'Player wages',amount:'850000',date:'2025-09-30',status:'Paid'},{name:'Academy allocation',type:'Budget',category:'Academy',amount:'600000',status:'Planned'}]},
 {id:'academy',title:'Youth Academy',singular:'Academy player',fields:[field('name','Player name'),field('age','Age','number'),field('level','Development stage','select',['Grassroots','U15','U17','U19','Senior training']),field('skills','Skill development (%)','number'),field('school','School progress'),field('discipline','Discipline'),field('trial','Trial results','textarea'),field('readiness','Promotion readiness (%)','number'),field('report','Talent growth report','textarea')],seed:[{name:'Brian Kamau',age:'17',level:'U19',skills:'78',school:'Good academic standing',discipline:'Good',readiness:'82',trial:'Strong pace and ball control',report:'Ready for supervised senior training.'}]},
 {id:'medical',title:'Injury & Recovery',singular:'Medical record',fields:[field('name','Player name'),field('injury','Injury type'),field('date','Injury date','date'),field('treatment','Treatment plan','textarea'),field('progress','Recovery progress (%)','number'),field('tests','Fitness test results','textarea'),field('returnDate','Expected return-to-play','date'),field('status','Medical status','select',['In treatment','Rehabilitation','Fitness testing','Cleared']),field('clinician','Responsible clinician')],seed:[{name:'Kevin Mwangi',injury:'Hamstring strain',date:'2025-09-15',progress:'65',returnDate:'2025-10-20',status:'Rehabilitation',treatment:'Physiotherapy and progressive loading',tests:'Awaiting sprint assessment',clinician:'Club medical team'}]},
 {id:'matches',title:'Match Analysis',singular:'Match report',fields:[field('name','Opponent / fixture'),field('date','Match date','date'),field('result','Result'),field('possession','Possession (%)','number'),field('chances','Chances created','number'),field('errors','Defensive errors','number'),field('setPieces','Set-piece success (%)','number'),field('ratings','Player ratings','textarea'),field('weaknesses','Tactical weaknesses','textarea'),field('actions','Follow-up decisions','textarea'),field('report','Match report','textarea')],seed:[{name:'City United',date:'2025-09-28',result:'2–1 Win',possession:'58',chances:'12',errors:'2',setPieces:'40',ratings:'Otieno 8/10; Mwangi 7/10',weaknesses:'Space behind fullbacks',actions:'Focus on defensive transition drills.'}]},
 {id:'community',title:'Fans & Community',singular:'Community activity',fields:[field('name','Event or initiative'),field('date','Date','date'),field('type','Type','select',['Matchday','Community outreach','CSR project','Youth clinic','Social media']),field('attendance','Attendance','number'),field('engagement','Social engagements','number'),field('budget','Budget (KES)','number'),field('owner','Owner'),field('impact','Community impact','textarea'),field('status','Status','select',['Planned','In progress','Completed'])],seed:[{name:'Youth football clinic',date:'2025-09-20',type:'Youth clinic',attendance:'120',engagement:'650',budget:'45000',owner:'Community Lead',status:'Completed',impact:'120 young participants across four schools.'}]},
 {id:'scouting',title:'Scouting & Recruitment',singular:'Scouting report',fields:[field('name','Prospect name'),field('age','Age','number'),field('position','Position'),field('club','Current club'),field('strengths','Strengths','textarea'),field('weaknesses','Weaknesses','textarea'),field('value','Transfer value (KES)','number'),field('injuries','Injury history','textarea'),field('character','Character assessment','textarea'),field('rating','Scout rating (0–100)','number'),field('status','Recruitment stage','select',['Watching','Shortlisted','Trial','Negotiating','Signed','Not proceeding'])],seed:[{name:'Peter Ouma',age:'21',position:'Defender',club:'Coastal FC',strengths:'Aerial ability and positioning',weaknesses:'Passing under pressure',value:'1500000',injuries:'No known recent injuries',character:'Strong team ethic',rating:'83',status:'Shortlisted'}]}
];
export const initialFootballRecords = (): Record<string,FootballRow[]> => Object.fromEntries(footballSections.map(section=>[section.id,section.seed.map((row,index)=>({id:`${section.id}-${index}`, ...row}))]));
