# Generated by Django 5.2.17 on 2026-10-07 16:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('campaign_type', models.CharField(choices=[('political', 'Political'), ('marketing', 'Marketing'), ('awareness', 'Awareness'), ('fundraising', 'Fundraising'), ('other', 'Other')], default='political', max_length=15)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=15)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('budget_spent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('target_audience', models.TextField(blank=True)),
                ('key_messages', models.JSONField(blank=True, default=list)),
                ('goals', models.JSONField(blank=True, default=list)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('activity_type', models.CharField(choices=[('event', 'Event'), ('meeting', 'Meeting'), ('canvassing', 'Canvassing'), ('social_media', 'Social Media'), ('press', 'Press Release'), ('fundraiser', 'Fundraiser'), ('ad', 'Advertisement'), ('other', 'Other')], default='event', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=300)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reach', models.PositiveIntegerField(default=0)),
                ('engagement', models.PositiveIntegerField(default=0)),
                ('outcome', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='campaign.campaign')),
            ],
            options={
                'db_table': 'campaign_activities',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PoliticalContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(choices=[('supporter', 'Supporter'), ('donor', 'Donor'), ('volunteer', 'Volunteer'), ('opponent', 'Opponent'), ('neutral', 'Neutral'), ('media', 'Media'), ('official', 'Official')], default='neutral', max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('constituency', models.CharField(blank=True, max_length=200)),
                ('influence_score', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('last_contact', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='campaign.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='political_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'political_contacts',
                'ordering': ['name'],
            },
        ),
    ]
