# Generated by Django 5.2.17 on 2026-10-07 16:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballClub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('league', models.CharField(choices=[('premier_league', 'Premier League'), ('la_liga', 'La Liga'), ('serie_a', 'Serie A'), ('bundesliga', 'Bundesliga'), ('ligue_1', 'Ligue 1'), ('championship', 'Championship'), ('other', 'Other')], default='other', max_length=50)),
                ('league_position', models.CharField(blank=True, max_length=100)),
                ('stadium', models.CharField(blank=True, max_length=200)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('records', models.JSONField(blank=True, default=dict)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='football_clubs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'football_clubs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opponent', models.CharField(max_length=200)),
                ('match_date', models.DateTimeField()),
                ('home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('is_home', models.BooleanField(default=True)),
                ('competition', models.CharField(choices=[('league', 'League'), ('cup', 'Cup'), ('champions_league', 'Champions League'), ('europa_league', 'Europa League'), ('friendly', 'Friendly')], default='league', max_length=30)),
                ('result', models.CharField(choices=[('W', 'Win'), ('D', 'Draw'), ('L', 'Loss'), ('P', 'Pending')], default='P', max_length=1)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('attendance', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='football.footballclub')),
            ],
            options={
                'db_table': 'football_matches',
                'ordering': ['-match_date'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('CB', 'Centre-Back'), ('LB', 'Left-Back'), ('RB', 'Right-Back'), ('CDM', 'Defensive Mid'), ('CM', 'Central Mid'), ('CAM', 'Attacking Mid'), ('LW', 'Left Wing'), ('RW', 'Right Wing'), ('ST', 'Striker'), ('CF', 'Centre Forward')], max_length=10)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True)),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contract_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('injured', 'Injured'), ('suspended', 'Suspended'), ('on_loan', 'On Loan'), ('transfer', 'Transfer Listed')], default='active', max_length=20)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='football.footballclub')),
            ],
            options={
                'db_table': 'football_players',
                'ordering': ['position', 'name'],
                'unique_together': {('club', 'jersey_number')},
            },
        ),
    ]
