# Generated by Django 5.2.17 on 2026-10-10 16:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('group_type', models.CharField(choices=[('journaling', 'Group Journaling'), ('project', 'Shared Project'), ('coaching', 'Coaching Pod'), ('faithflow', 'FaithFlow')], default='journaling', max_length=15)),
                ('description', models.TextField(blank=True)),
                ('is_private', models.BooleanField(default=False)),
                ('member_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupJournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField()),
                ('prompt_used', models.CharField(blank=True, max_length=400)),
                ('mood', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='organizational.communitygroup')),
            ],
            options={
                'db_table': 'group_journal_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('scope', models.CharField(choices=[('company', 'Company'), ('department', 'Department'), ('team', 'Team'), ('individual', 'Individual')], default='team', max_length=15)),
                ('quarter', models.CharField(blank=True, max_length=2)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('behind', 'Behind'), ('completed', 'Completed')], default='on_track', max_length=15)),
                ('overall_progress', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'objectives',
                'ordering': ['year', 'quarter', 'title'],
            },
        ),
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=400)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='not_started', max_length=15)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='organizational.objective')),
            ],
            options={
                'db_table': 'key_results',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='FaithFlowStreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('devotional_completed', models.BooleanField(default=False)),
                ('mindfulness_minutes', models.PositiveSmallIntegerField(default=0)),
                ('gratitude_note', models.TextField(blank=True)),
                ('scripture_verse', models.CharField(blank=True, max_length=400)),
                ('reflection', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faithflow_streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'faithflow_streaks',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RemoteTimesheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hours_logged', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tasks_summary', models.TextField(blank=True)),
                ('productivity_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets', to='organizational.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'remote_timesheets',
                'ordering': ['-date'],
                'unique_together': {('user', 'date', 'team')},
            },
        ),
    ]
