# Generated by Django 5.2.17 on 2026-10-07 16:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('target_count', models.PositiveIntegerField(default=1)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'habits',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('number', 'Number'), ('percentage', '%'), ('currency', 'Currency'), ('hours', 'Hours'), ('days', 'Days'), ('custom', 'Custom')], default='number', max_length=15)),
                ('custom_unit', models.CharField(blank=True, max_length=30)),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kpis',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PersonalGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('health', 'Health'), ('finance', 'Finance'), ('career', 'Career'), ('relationships', 'Relationships'), ('learning', 'Learning'), ('personal', 'Personal'), ('spiritual', 'Spiritual'), ('other', 'Other')], default='personal', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='not_started', max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('milestones', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personal_goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('mood', models.PositiveSmallIntegerField(blank=True, choices=[(1, '😞'), (2, '😐'), (3, '🙂'), (4, '😊'), (5, '🤩')], null=True)),
                ('energy_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gratitude', models.TextField(blank=True)),
                ('wins', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('tomorrow_focus', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_entries',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=1)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='personal_tracker.habit')),
            ],
            options={
                'db_table': 'habit_logs',
                'ordering': ['-date'],
                'unique_together': {('habit', 'date')},
            },
        ),
    ]
