# Generated by Django 5.2.17 on 2026-10-07 16:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('timeframe', models.CharField(choices=[('short', 'Short-term (0–6 months)'), ('medium', 'Medium-term (6–24 months)'), ('long', 'Long-term (2–5 years)'), ('vision', 'Vision (5+ years)')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('achieved', 'Achieved'), ('paused', 'Paused'), ('abandoned', 'Abandoned')], default='active', max_length=15)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('resources', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'career_goals',
                'ordering': ['timeframe', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutiveLearning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('author_or_provider', models.CharField(blank=True, max_length=200)),
                ('learning_type', models.CharField(choices=[('book', 'Book'), ('course', 'Course'), ('seminar', 'Seminar'), ('podcast', 'Podcast'), ('article', 'Article'), ('mentoring', 'Mentoring'), ('workshop', 'Workshop'), ('other', 'Other')], default='book', max_length=15)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='planned', max_length=15)),
                ('key_takeaways', models.TextField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('time_invested_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_learning', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'executive_learning',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InnovationIdea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('problem_statement', models.TextField(blank=True)),
                ('proposed_solution', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('idea', 'Idea'), ('researching', 'Researching'), ('prototyping', 'Prototyping'), ('testing', 'Testing'), ('launched', 'Launched'), ('archived', 'Archived')], default='idea', max_length=15)),
                ('impact_potential', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('disruptive', 'Disruptive')], default='medium', max_length=15)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('votes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innovation_ideas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'innovation_ideas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('soft', 'Soft Skills'), ('leadership', 'Leadership'), ('language', 'Language'), ('industry', 'Industry Knowledge'), ('tool', 'Tool/Software')], default='technical', max_length=15)),
                ('current_level', models.PositiveSmallIntegerField(choices=[(1, 'Beginner'), (2, 'Novice'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')], default=1)),
                ('target_level', models.PositiveSmallIntegerField(choices=[(1, 'Beginner'), (2, 'Novice'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')], default=3)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('learning_resources', models.JSONField(blank=True, default=list)),
                ('progress_notes', models.TextField(blank=True)),
                ('is_certified', models.BooleanField(default=False)),
                ('certification_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skills',
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
