# Generated by Django 5.2.17 on 2026-10-07 16:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BurnoutAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('triggered_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burnout_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'burnout_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('exercise', 'Exercise'), ('meditation', 'Meditation/Mindfulness'), ('social', 'Social Connection'), ('nature', 'Nature/Outdoors'), ('hobby', 'Hobby'), ('rest', 'Rest/Sleep'), ('therapy', 'Therapy/Counseling'), ('vacation', 'Vacation/Time Off'), ('other', 'Other')], default='other', max_length=15)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('as_needed', 'As Needed')], default='weekly', max_length=10)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('effectiveness_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_performed', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recovery_activities',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BurnoutAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('emotional_exhaustion', models.PositiveSmallIntegerField(default=0)),
                ('depersonalization', models.PositiveSmallIntegerField(default=0)),
                ('personal_accomplishment', models.PositiveSmallIntegerField(default=10)),
                ('work_hours_per_week', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('sleep_hours_per_night', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('exercise_days_per_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('overall_score', models.PositiveSmallIntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk'), ('critical', 'Critical')], default='low', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burnout_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'burnout_assessments',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WorkloadEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hours_worked', models.DecimalField(decimal_places=1, default=8, max_digits=4)),
                ('stress_level', models.PositiveSmallIntegerField(default=5)),
                ('focus_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('meetings_count', models.PositiveSmallIntegerField(default=0)),
                ('tasks_completed', models.PositiveSmallIntegerField(default=0)),
                ('tasks_pending', models.PositiveSmallIntegerField(default=0)),
                ('main_stressors', models.JSONField(blank=True, default=list)),
                ('highlights', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workload_entries',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
